const orderStatusArr = [
    'CREATED',//0
    'DISPATCHING',//1
    'DISPATCHED',//2
    'BUTLER_RECEIVED',//3
    'BUTLER_PICKING_CAR',//4
    'BUTLER_ARRIVE_TO_PICK_CAR',//5
    'BUTLER_PICKED_CAR',//6
    'BUTLER_DRIVING_CAR_TO_CHARGE',//7
    'BUTLER_ARRIVE_CHARGING_STATION',//8
    'BUTLER_START_CHARGING_CAR',//9
    'BUTLER_CHARGING_CAR',//10
    'BUTLER_FINISHED_CHARGING',//11
    'BUTLER_RETURNING_CAR',//12
    'BUTLER_ARRIVE_TO_RETURN',//13
    'CAR_RETURNED',//14
    'WAITING_BUTLER_CONFIRM_PAYMENT_DONE',//15
    'PAID',//
    'USER_FINISHED',//
    'BUTLER_FINISHED',//
    'CANCELED'
];
export default orderStatusArr;
